### ISSUE TITLE
Architecture violations without references

### ISSUE THREAD

**Issue by perryqh** [alexevanczuk/packs#121]
If a pack's `package.yml` contains a dependency to a pack in a higher architecture layer and there are no actual references to pack in the higher architecture error, `pks check` will not report a violation.

An [example](https://github.com/perryqh/packs-architecture-violation/tree/ph/pks-check-ref)

- the `utility` layer is [below](https://github.com/perryqh/packs-architecture-violation/blob/ph/pks-check-ref/packwerk.yml#L4)`domain`
- the packs/utility_pack `package.yml` [lists](https://github.com/perryqh/packs-architecture-violation/blob/ph/pks-check-ref/packs/utility_pack/package.yml#L6) `packs/domain_pack` as a dependency
- there are [no actual references](https://github.com/perryqh/packs-architecture-violation/blob/ph/pks-check-ref/packs/utility_pack/app/models/utility.rb#L3) to packs/domain_pack in packs/utility_pack
- `pks check` returns “No violations detected!”

`bin/packwerk validate` reports the architecture violation even if the pack isn’t referenced. `pks check` does not report a violation.

The source code [indicates](https://github.com/alexevanczuk/packs/blob/fc04bb46f0a8c2c953d20034afde1e87743c2e53/src/packs/checker.rs#L82C11-L82C11) that “checkers” only deal with references and not declared package dependencies. Is this intended behavior?

`pks check-unnecessary-dependencies` does show that the dependency is unnecessary. Are we to run `pks [validate, check, check-unnecessary-dependencies]` as a replacement for `packwerk [validate, check]`?

**Comment by alexevanczuk** [comment]
Hey thanks for the issue @perryqh 

I think you're right that the checker should only be looking at references and instead the validations should complain about dependencies that violate the architectural layer rules.

The goal for packs has been for `validate` and `check` to always match what `packwerk` does so it can be used as a drop in replacement and for non-packwerk commands to be independent. Even though that's less ergonomic right now, it's mostly to optimize for being a drop in for packwerk. In the future, I think there should only be a single command: `packs check` that does everything (with users being able to opt out of certain kinds things via `packs.yml` or via CLI flags).

**Comment by perryqh** [comment]
@alexevanczuk I'm willing to pick up this effort. What are your thoughts on next steps? Drive towards `packs` being a drop in replacement or a single command of `packs check`?
