### ISSUE TITLE
`pack validate` panics when an item of `dependencies` doesn't exist

### ISSUE THREAD

**Issue by technicalpickles** [alexevanczuk/packs#130]
Consider a repo with a `package.yml` that has the a typo in a dependency:

```
❯ pks validate
thread 'main' panicked at src/packs/checker/dependency.rs:67:41:
/Users/josh.nichols/workspace/someapp/package.yml has 'pack/non-existent in its dependencies, but that pack cannot be found. Try `packs list-packs` to debug.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This seems like it is a condition that validate will run in, so probably should be caught and displayed instead of an error with debug info.

**Comment by technicalpickles** [comment]
Kinda related, but the file path should be relative to the current directory, rather than absolute. `packs check` seems to do this.

**Comment by alexevanczuk** [comment]
Thank you for reporting! Could you or @perryqh submit a PR to fix?

**Comment by perryqh** [comment]
Addressed by https://github.com/alexevanczuk/packs/pull/131
