### ISSUE TITLE
pks seems to hallucinate when used with experimental parser and constants are defined outside of the application

### ISSUE THREAD

**Issue by exterm** [alexevanczuk/packs#147]
Examples:

> Dependency violation: `::String` belongs to `.`, but `packs/domain/internal_users/package.yml` does not specify a dependency on `.`

> Architecture violation: `::Rails` belongs to `.` (whose layer is `application`) cannot be accessed from `packs/domain/geography` (whose layer is `domain`)

Is this expected behavior? I mean, it _is_ called "experimental".

**Comment by alexevanczuk** [comment]
Hey @exterm , thanks for opening an issue!

TLDR: This means that in the `.` pack, your application is monkey patching `::String` and `::Rails`.
Therefore, the experimental parser considers this to be a definition. 

This document has all the info about what the experimental parser considers a definition.
https://github.com/alexevanczuk/packs/blob/main/EXPERIMENTAL_PARSER_USAGE.md

If you'd like to ignore this definition, the link above documents the API to do so!

**Comment by exterm** [comment]
Thanks, will look into it!

**Comment by exterm** [comment]
Can I somehow have `pks` output which file it resolved a constant to?

**Comment by alexevanczuk** [comment]
@exterm Definitely. Check out `pks list-definitions`! It was added for this specific purpose to make it easier to understand how each parser determined where a constant is defined.

**Comment by exterm** [comment]
Perfect!

After some reflection, it's really interesting to see this behavior. Packwerk doesn't fall for redefinitions / monkeypatching because it resolves constants like zeitwerk loads them, so it always resolves to the "main" definition. Ruby itself doesn't even have a "main" definition, that's pretty much a zeitwerk concept...

I hadn't thought about this before.

I can't currently come up with a way to fix this problem in `packs` without manual configuration, but I'll think a little more about it.
