### ISSUE TITLE
VSCode Extension does not print all errors in a file

### ISSUE THREAD

**Issue by alexevanczuk** [alexevanczuk/packs#190]
When using the vscode extension https://github.com/rubyatscale/packwerk-vscode and setting `pks check` to be the executable, I'm noticing that it's only highlighting one of the errors in this file.

Not sure what changed, but it looks like the output of `pks check` is different than `bin/packwerk` and the regex matching in the extension no longer matches.

@perryqh Are you seeing this on your side too? This would be nice to fix since `pks check` is a lot snappier in vscode than `bin/packwerk check`.

**Comment by perryqh** [comment]
I don't use the extension, but maybe I should be. I'll take a look.
