### ISSUE TITLE
Packs doesn't detect reference when mixing constant references and method calls

### ISSUE THREAD

**Issue by oleg-vinted** [alexevanczuk/packs#215]
Here's an example, we have two files in two different packages, with no dependencies defined:

```ruby
class Foo
  def foo
    # should be a violation, but isn't:
    Bar::ADAPTER['default']::INSTANCE
  end
end
```

```ruby
# this file doesn't really matter, it's just some minimal
# implementation so that the code above makes sense

module Bar
  module DefaultAdapter
    INSTANCE = 'fake instance'
  end

  ADAPTER = {
    'default' => DefaultAdapter,
  }
end
```

`Bar::ADAPTER` should be a violation, but it's not detected by Packs. Packwerk does detect this violation.

Minimal reproduction repo: https://github.com/oleg-vinted/packs-repro.

**Comment by alexevanczuk** [comment]
Interesting, does this happen when you just reference `ADAPTER` alone? e.g.
```
class Foo
  def foo
    # should be a violation, but isn't:
    Bar::ADAPTER
  end
end

module Bar
  ADAPTER = 1
end
```

**Comment by alexevanczuk** [comment]
Interesting – my guess is something in the reference collection logic isn't picking that up as a reference in that case. I could look into it at some point but also feel free to shoot a PR over and will look at it right away!
